
namespace DbProjectFinal
{
    partial class ExternalAdd
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ExternalAdd));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.semesterInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.accountInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.companyInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2Button1 = new Guna.UI2.WinForms.Guna2Button();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.phoneInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addressInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.emailInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // semesterInput
            // 
            this.semesterInput.AcceptsReturn = false;
            this.semesterInput.AcceptsTab = false;
            this.semesterInput.AnimationSpeed = 200;
            this.semesterInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.semesterInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.semesterInput.AutoSizeHeight = true;
            this.semesterInput.BackColor = System.Drawing.Color.Transparent;
            this.semesterInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("semesterInput.BackgroundImage")));
            this.semesterInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.semesterInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.semesterInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.semesterInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.semesterInput.BorderRadius = 15;
            this.semesterInput.BorderThickness = 3;
            this.semesterInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.semesterInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.semesterInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.semesterInput.DefaultText = "";
            this.semesterInput.FillColor = System.Drawing.Color.White;
            this.semesterInput.HideSelection = true;
            this.semesterInput.IconLeft = null;
            this.semesterInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.semesterInput.IconPadding = 10;
            this.semesterInput.IconRight = null;
            this.semesterInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.semesterInput.Lines = new string[0];
            this.semesterInput.Location = new System.Drawing.Point(97, 250);
            this.semesterInput.MaxLength = 32767;
            this.semesterInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.semesterInput.Modified = false;
            this.semesterInput.Multiline = false;
            this.semesterInput.Name = "semesterInput";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.semesterInput.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.semesterInput.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.semesterInput.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.semesterInput.OnIdleState = stateProperties32;
            this.semesterInput.Padding = new System.Windows.Forms.Padding(3);
            this.semesterInput.PasswordChar = '\0';
            this.semesterInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.semesterInput.PlaceholderText = "Semester";
            this.semesterInput.ReadOnly = false;
            this.semesterInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.semesterInput.SelectedText = "";
            this.semesterInput.SelectionLength = 0;
            this.semesterInput.SelectionStart = 0;
            this.semesterInput.ShortcutsEnabled = true;
            this.semesterInput.Size = new System.Drawing.Size(152, 39);
            this.semesterInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.semesterInput.TabIndex = 34;
            this.semesterInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.semesterInput.TextMarginBottom = 0;
            this.semesterInput.TextMarginLeft = 3;
            this.semesterInput.TextMarginTop = 1;
            this.semesterInput.TextPlaceholder = "Semester";
            this.semesterInput.UseSystemPasswordChar = false;
            this.semesterInput.WordWrap = true;
            // 
            // accountInput
            // 
            this.accountInput.AcceptsReturn = false;
            this.accountInput.AcceptsTab = false;
            this.accountInput.AnimationSpeed = 200;
            this.accountInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.accountInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.accountInput.AutoSizeHeight = true;
            this.accountInput.BackColor = System.Drawing.Color.Transparent;
            this.accountInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("accountInput.BackgroundImage")));
            this.accountInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.accountInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.accountInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.accountInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.accountInput.BorderRadius = 15;
            this.accountInput.BorderThickness = 3;
            this.accountInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.accountInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.accountInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.accountInput.DefaultText = "";
            this.accountInput.FillColor = System.Drawing.Color.White;
            this.accountInput.HideSelection = true;
            this.accountInput.IconLeft = null;
            this.accountInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.accountInput.IconPadding = 10;
            this.accountInput.IconRight = null;
            this.accountInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.accountInput.Lines = new string[0];
            this.accountInput.Location = new System.Drawing.Point(12, 409);
            this.accountInput.MaxLength = 32767;
            this.accountInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.accountInput.Modified = false;
            this.accountInput.Multiline = false;
            this.accountInput.Name = "accountInput";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.accountInput.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.accountInput.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.accountInput.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.accountInput.OnIdleState = stateProperties36;
            this.accountInput.Padding = new System.Windows.Forms.Padding(3);
            this.accountInput.PasswordChar = '\0';
            this.accountInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.accountInput.PlaceholderText = "Account Number";
            this.accountInput.ReadOnly = false;
            this.accountInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.accountInput.SelectedText = "";
            this.accountInput.SelectionLength = 0;
            this.accountInput.SelectionStart = 0;
            this.accountInput.ShortcutsEnabled = true;
            this.accountInput.Size = new System.Drawing.Size(336, 39);
            this.accountInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.accountInput.TabIndex = 32;
            this.accountInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.accountInput.TextMarginBottom = 0;
            this.accountInput.TextMarginLeft = 3;
            this.accountInput.TextMarginTop = 1;
            this.accountInput.TextPlaceholder = "Account Number";
            this.accountInput.UseSystemPasswordChar = false;
            this.accountInput.WordWrap = true;
            // 
            // companyInput
            // 
            this.companyInput.AcceptsReturn = false;
            this.companyInput.AcceptsTab = false;
            this.companyInput.AnimationSpeed = 200;
            this.companyInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.companyInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.companyInput.AutoSizeHeight = true;
            this.companyInput.BackColor = System.Drawing.Color.Transparent;
            this.companyInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("companyInput.BackgroundImage")));
            this.companyInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.companyInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.companyInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.companyInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.companyInput.BorderRadius = 15;
            this.companyInput.BorderThickness = 3;
            this.companyInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.companyInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.companyInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.companyInput.DefaultText = "";
            this.companyInput.FillColor = System.Drawing.Color.White;
            this.companyInput.HideSelection = true;
            this.companyInput.IconLeft = null;
            this.companyInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.companyInput.IconPadding = 10;
            this.companyInput.IconRight = null;
            this.companyInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.companyInput.Lines = new string[0];
            this.companyInput.Location = new System.Drawing.Point(12, 354);
            this.companyInput.MaxLength = 32767;
            this.companyInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.companyInput.Modified = false;
            this.companyInput.Multiline = false;
            this.companyInput.Name = "companyInput";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.companyInput.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.companyInput.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.companyInput.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.companyInput.OnIdleState = stateProperties40;
            this.companyInput.Padding = new System.Windows.Forms.Padding(3);
            this.companyInput.PasswordChar = '\0';
            this.companyInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.companyInput.PlaceholderText = "Company";
            this.companyInput.ReadOnly = false;
            this.companyInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.companyInput.SelectedText = "";
            this.companyInput.SelectionLength = 0;
            this.companyInput.SelectionStart = 0;
            this.companyInput.ShortcutsEnabled = true;
            this.companyInput.Size = new System.Drawing.Size(336, 39);
            this.companyInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.companyInput.TabIndex = 31;
            this.companyInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.companyInput.TextMarginBottom = 0;
            this.companyInput.TextMarginLeft = 3;
            this.companyInput.TextMarginTop = 1;
            this.companyInput.TextPlaceholder = "Company";
            this.companyInput.UseSystemPasswordChar = false;
            this.companyInput.WordWrap = true;
            // 
            // guna2Button1
            // 
            this.guna2Button1.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button1.BorderRadius = 22;
            this.guna2Button1.CheckedState.Parent = this.guna2Button1;
            this.guna2Button1.CustomImages.Parent = this.guna2Button1;
            this.guna2Button1.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button1.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button1.DisabledState.Parent = this.guna2Button1;
            this.guna2Button1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.guna2Button1.Font = new System.Drawing.Font("Palatino Linotype", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2Button1.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.guna2Button1.HoverState.Parent = this.guna2Button1;
            this.guna2Button1.Location = new System.Drawing.Point(70, 472);
            this.guna2Button1.Name = "guna2Button1";
            this.guna2Button1.ShadowDecoration.Parent = this.guna2Button1;
            this.guna2Button1.Size = new System.Drawing.Size(212, 37);
            this.guna2Button1.TabIndex = 30;
            this.guna2Button1.Text = "Add Details";
            this.guna2Button1.Click += new System.EventHandler(this.guna2Button1_Click);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 20;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(31, 29);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(297, 8);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.TabIndex = 29;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 20;
            this.bunifuImageButton2.ZoomSpeed = 10;
            this.bunifuImageButton2.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 20;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(95, 83);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(12, 51);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.TabIndex = 28;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 20;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Impact", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(133, 86);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(201, 36);
            this.label1.TabIndex = 27;
            this.label1.Text = "External Details";
            // 
            // phoneInput
            // 
            this.phoneInput.AcceptsReturn = false;
            this.phoneInput.AcceptsTab = false;
            this.phoneInput.AnimationSpeed = 200;
            this.phoneInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phoneInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phoneInput.AutoSizeHeight = true;
            this.phoneInput.BackColor = System.Drawing.Color.Transparent;
            this.phoneInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phoneInput.BackgroundImage")));
            this.phoneInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.phoneInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.phoneInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.phoneInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.phoneInput.BorderRadius = 15;
            this.phoneInput.BorderThickness = 3;
            this.phoneInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phoneInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.phoneInput.DefaultText = "";
            this.phoneInput.FillColor = System.Drawing.Color.White;
            this.phoneInput.HideSelection = true;
            this.phoneInput.IconLeft = null;
            this.phoneInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneInput.IconPadding = 10;
            this.phoneInput.IconRight = null;
            this.phoneInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phoneInput.Lines = new string[0];
            this.phoneInput.Location = new System.Drawing.Point(97, 205);
            this.phoneInput.MaxLength = 32767;
            this.phoneInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.phoneInput.Modified = false;
            this.phoneInput.Multiline = false;
            this.phoneInput.Name = "phoneInput";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneInput.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phoneInput.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneInput.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phoneInput.OnIdleState = stateProperties44;
            this.phoneInput.Padding = new System.Windows.Forms.Padding(3);
            this.phoneInput.PasswordChar = '\0';
            this.phoneInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phoneInput.PlaceholderText = "Phone Number";
            this.phoneInput.ReadOnly = false;
            this.phoneInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phoneInput.SelectedText = "";
            this.phoneInput.SelectionLength = 0;
            this.phoneInput.SelectionStart = 0;
            this.phoneInput.ShortcutsEnabled = true;
            this.phoneInput.Size = new System.Drawing.Size(152, 39);
            this.phoneInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phoneInput.TabIndex = 26;
            this.phoneInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.phoneInput.TextMarginBottom = 0;
            this.phoneInput.TextMarginLeft = 3;
            this.phoneInput.TextMarginTop = 1;
            this.phoneInput.TextPlaceholder = "Phone Number";
            this.phoneInput.UseSystemPasswordChar = false;
            this.phoneInput.WordWrap = true;
            // 
            // addressInput
            // 
            this.addressInput.AcceptsReturn = false;
            this.addressInput.AcceptsTab = false;
            this.addressInput.AnimationSpeed = 200;
            this.addressInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressInput.AutoSizeHeight = true;
            this.addressInput.BackColor = System.Drawing.Color.Transparent;
            this.addressInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressInput.BackgroundImage")));
            this.addressInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.addressInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.addressInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.addressInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.addressInput.BorderRadius = 15;
            this.addressInput.BorderThickness = 3;
            this.addressInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressInput.DefaultText = "";
            this.addressInput.FillColor = System.Drawing.Color.White;
            this.addressInput.HideSelection = true;
            this.addressInput.IconLeft = null;
            this.addressInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressInput.IconPadding = 10;
            this.addressInput.IconRight = null;
            this.addressInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressInput.Lines = new string[0];
            this.addressInput.Location = new System.Drawing.Point(12, 298);
            this.addressInput.MaxLength = 32767;
            this.addressInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressInput.Modified = false;
            this.addressInput.Multiline = false;
            this.addressInput.Name = "addressInput";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressInput.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressInput.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressInput.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressInput.OnIdleState = stateProperties48;
            this.addressInput.Padding = new System.Windows.Forms.Padding(3);
            this.addressInput.PasswordChar = '\0';
            this.addressInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressInput.PlaceholderText = "Address";
            this.addressInput.ReadOnly = false;
            this.addressInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressInput.SelectedText = "";
            this.addressInput.SelectionLength = 0;
            this.addressInput.SelectionStart = 0;
            this.addressInput.ShortcutsEnabled = true;
            this.addressInput.Size = new System.Drawing.Size(336, 39);
            this.addressInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressInput.TabIndex = 25;
            this.addressInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.addressInput.TextMarginBottom = 0;
            this.addressInput.TextMarginLeft = 3;
            this.addressInput.TextMarginTop = 1;
            this.addressInput.TextPlaceholder = "Address";
            this.addressInput.UseSystemPasswordChar = false;
            this.addressInput.WordWrap = true;
            // 
            // nameInput
            // 
            this.nameInput.AcceptsReturn = false;
            this.nameInput.AcceptsTab = false;
            this.nameInput.AnimationSpeed = 200;
            this.nameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameInput.AutoSizeHeight = true;
            this.nameInput.BackColor = System.Drawing.Color.Transparent;
            this.nameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameInput.BackgroundImage")));
            this.nameInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.nameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.nameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.nameInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.nameInput.BorderRadius = 15;
            this.nameInput.BorderThickness = 3;
            this.nameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameInput.DefaultText = "";
            this.nameInput.FillColor = System.Drawing.Color.White;
            this.nameInput.HideSelection = true;
            this.nameInput.IconLeft = null;
            this.nameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameInput.IconPadding = 10;
            this.nameInput.IconRight = null;
            this.nameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameInput.Lines = new string[0];
            this.nameInput.Location = new System.Drawing.Point(12, 160);
            this.nameInput.MaxLength = 32767;
            this.nameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameInput.Modified = false;
            this.nameInput.Multiline = false;
            this.nameInput.Name = "nameInput";
            stateProperties49.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameInput.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameInput.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameInput.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameInput.OnIdleState = stateProperties52;
            this.nameInput.Padding = new System.Windows.Forms.Padding(3);
            this.nameInput.PasswordChar = '\0';
            this.nameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameInput.PlaceholderText = "Name";
            this.nameInput.ReadOnly = false;
            this.nameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameInput.SelectedText = "";
            this.nameInput.SelectionLength = 0;
            this.nameInput.SelectionStart = 0;
            this.nameInput.ShortcutsEnabled = true;
            this.nameInput.Size = new System.Drawing.Size(152, 39);
            this.nameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nameInput.TabIndex = 24;
            this.nameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.nameInput.TextMarginBottom = 0;
            this.nameInput.TextMarginLeft = 3;
            this.nameInput.TextMarginTop = 1;
            this.nameInput.TextPlaceholder = "Name";
            this.nameInput.UseSystemPasswordChar = false;
            this.nameInput.WordWrap = true;
            // 
            // emailInput
            // 
            this.emailInput.AcceptsReturn = false;
            this.emailInput.AcceptsTab = false;
            this.emailInput.AnimationSpeed = 200;
            this.emailInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailInput.AutoSizeHeight = true;
            this.emailInput.BackColor = System.Drawing.Color.Transparent;
            this.emailInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailInput.BackgroundImage")));
            this.emailInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.emailInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderRadius = 15;
            this.emailInput.BorderThickness = 3;
            this.emailInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.emailInput.DefaultText = "";
            this.emailInput.FillColor = System.Drawing.Color.White;
            this.emailInput.HideSelection = true;
            this.emailInput.IconLeft = null;
            this.emailInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.IconPadding = 10;
            this.emailInput.IconRight = null;
            this.emailInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.Lines = new string[0];
            this.emailInput.Location = new System.Drawing.Point(196, 160);
            this.emailInput.MaxLength = 32767;
            this.emailInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailInput.Modified = false;
            this.emailInput.Multiline = false;
            this.emailInput.Name = "emailInput";
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailInput.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnIdleState = stateProperties56;
            this.emailInput.Padding = new System.Windows.Forms.Padding(3);
            this.emailInput.PasswordChar = '\0';
            this.emailInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailInput.PlaceholderText = "Email";
            this.emailInput.ReadOnly = false;
            this.emailInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailInput.SelectedText = "";
            this.emailInput.SelectionLength = 0;
            this.emailInput.SelectionStart = 0;
            this.emailInput.ShortcutsEnabled = true;
            this.emailInput.Size = new System.Drawing.Size(152, 39);
            this.emailInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailInput.TabIndex = 23;
            this.emailInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.emailInput.TextMarginBottom = 0;
            this.emailInput.TextMarginLeft = 3;
            this.emailInput.TextMarginTop = 1;
            this.emailInput.TextPlaceholder = "Email";
            this.emailInput.UseSystemPasswordChar = false;
            this.emailInput.WordWrap = true;
            // 
            // ExternalAdd
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(373, 531);
            this.Controls.Add(this.semesterInput);
            this.Controls.Add(this.accountInput);
            this.Controls.Add(this.companyInput);
            this.Controls.Add(this.guna2Button1);
            this.Controls.Add(this.bunifuImageButton2);
            this.Controls.Add(this.bunifuImageButton1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.phoneInput);
            this.Controls.Add(this.addressInput);
            this.Controls.Add(this.nameInput);
            this.Controls.Add(this.emailInput);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "ExternalAdd";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ExternalAdd";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox semesterInput;
        private Bunifu.UI.WinForms.BunifuTextBox accountInput;
        private Bunifu.UI.WinForms.BunifuTextBox companyInput;
        private Guna.UI2.WinForms.Guna2Button guna2Button1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox phoneInput;
        private Bunifu.UI.WinForms.BunifuTextBox addressInput;
        private Bunifu.UI.WinForms.BunifuTextBox nameInput;
        private Bunifu.UI.WinForms.BunifuTextBox emailInput;
    }
}