
namespace DbProjectFinal
{
    partial class FacultyAdd
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FacultyAdd));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.guna2Button1 = new Guna.UI2.WinForms.Guna2Button();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.eidInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.emailInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.fnameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lnameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.titleInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.designationInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.statusInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.codeInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // guna2Button1
            // 
            this.guna2Button1.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button1.BorderRadius = 22;
            this.guna2Button1.CheckedState.Parent = this.guna2Button1;
            this.guna2Button1.CustomImages.Parent = this.guna2Button1;
            this.guna2Button1.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button1.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button1.DisabledState.Parent = this.guna2Button1;
            this.guna2Button1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.guna2Button1.Font = new System.Drawing.Font("Palatino Linotype", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2Button1.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.guna2Button1.HoverState.Parent = this.guna2Button1;
            this.guna2Button1.Location = new System.Drawing.Point(85, 527);
            this.guna2Button1.Name = "guna2Button1";
            this.guna2Button1.ShadowDecoration.Parent = this.guna2Button1;
            this.guna2Button1.Size = new System.Drawing.Size(212, 37);
            this.guna2Button1.TabIndex = 18;
            this.guna2Button1.Text = "Add Details";
            this.guna2Button1.Click += new System.EventHandler(this.guna2Button1_Click);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 20;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(31, 29);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(313, 14);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.TabIndex = 17;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 20;
            this.bunifuImageButton2.ZoomSpeed = 10;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 20;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(95, 83);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(28, 57);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.TabIndex = 16;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 20;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Impact", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(149, 92);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(192, 36);
            this.label1.TabIndex = 15;
            this.label1.Text = "Faculty Details";
            // 
            // eidInput
            // 
            this.eidInput.AcceptsReturn = false;
            this.eidInput.AcceptsTab = false;
            this.eidInput.AnimationSpeed = 200;
            this.eidInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.eidInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.eidInput.AutoSizeHeight = true;
            this.eidInput.BackColor = System.Drawing.Color.Transparent;
            this.eidInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("eidInput.BackgroundImage")));
            this.eidInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderRadius = 15;
            this.eidInput.BorderThickness = 3;
            this.eidInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.eidInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.eidInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.eidInput.DefaultText = "";
            this.eidInput.FillColor = System.Drawing.Color.White;
            this.eidInput.HideSelection = true;
            this.eidInput.IconLeft = null;
            this.eidInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.eidInput.IconPadding = 10;
            this.eidInput.IconRight = null;
            this.eidInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.eidInput.Lines = new string[0];
            this.eidInput.Location = new System.Drawing.Point(113, 211);
            this.eidInput.MaxLength = 32767;
            this.eidInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.eidInput.Modified = false;
            this.eidInput.Multiline = false;
            this.eidInput.Name = "eidInput";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.eidInput.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.eidInput.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.eidInput.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.eidInput.OnIdleState = stateProperties4;
            this.eidInput.Padding = new System.Windows.Forms.Padding(3);
            this.eidInput.PasswordChar = '\0';
            this.eidInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.eidInput.PlaceholderText = "Employee Id";
            this.eidInput.ReadOnly = false;
            this.eidInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.eidInput.SelectedText = "";
            this.eidInput.SelectionLength = 0;
            this.eidInput.SelectionStart = 0;
            this.eidInput.ShortcutsEnabled = true;
            this.eidInput.Size = new System.Drawing.Size(152, 39);
            this.eidInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.eidInput.TabIndex = 14;
            this.eidInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.eidInput.TextMarginBottom = 0;
            this.eidInput.TextMarginLeft = 3;
            this.eidInput.TextMarginTop = 1;
            this.eidInput.TextPlaceholder = "Employee Id";
            this.eidInput.UseSystemPasswordChar = false;
            this.eidInput.WordWrap = true;
            // 
            // emailInput
            // 
            this.emailInput.AcceptsReturn = false;
            this.emailInput.AcceptsTab = false;
            this.emailInput.AnimationSpeed = 200;
            this.emailInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailInput.AutoSizeHeight = true;
            this.emailInput.BackColor = System.Drawing.Color.Transparent;
            this.emailInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailInput.BackgroundImage")));
            this.emailInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderRadius = 15;
            this.emailInput.BorderThickness = 3;
            this.emailInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.emailInput.DefaultText = "";
            this.emailInput.FillColor = System.Drawing.Color.White;
            this.emailInput.HideSelection = true;
            this.emailInput.IconLeft = null;
            this.emailInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.IconPadding = 10;
            this.emailInput.IconRight = null;
            this.emailInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.Lines = new string[0];
            this.emailInput.Location = new System.Drawing.Point(28, 304);
            this.emailInput.MaxLength = 32767;
            this.emailInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailInput.Modified = false;
            this.emailInput.Multiline = false;
            this.emailInput.Name = "emailInput";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailInput.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnIdleState = stateProperties8;
            this.emailInput.Padding = new System.Windows.Forms.Padding(3);
            this.emailInput.PasswordChar = '\0';
            this.emailInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailInput.PlaceholderText = "Email Address";
            this.emailInput.ReadOnly = false;
            this.emailInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailInput.SelectedText = "";
            this.emailInput.SelectionLength = 0;
            this.emailInput.SelectionStart = 0;
            this.emailInput.ShortcutsEnabled = true;
            this.emailInput.Size = new System.Drawing.Size(336, 39);
            this.emailInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailInput.TabIndex = 13;
            this.emailInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.emailInput.TextMarginBottom = 0;
            this.emailInput.TextMarginLeft = 3;
            this.emailInput.TextMarginTop = 1;
            this.emailInput.TextPlaceholder = "Email Address";
            this.emailInput.UseSystemPasswordChar = false;
            this.emailInput.WordWrap = true;
            // 
            // fnameInput
            // 
            this.fnameInput.AcceptsReturn = false;
            this.fnameInput.AcceptsTab = false;
            this.fnameInput.AnimationSpeed = 200;
            this.fnameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.fnameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.fnameInput.AutoSizeHeight = true;
            this.fnameInput.BackColor = System.Drawing.Color.Transparent;
            this.fnameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("fnameInput.BackgroundImage")));
            this.fnameInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderRadius = 15;
            this.fnameInput.BorderThickness = 3;
            this.fnameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.fnameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.fnameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.fnameInput.DefaultText = "";
            this.fnameInput.FillColor = System.Drawing.Color.White;
            this.fnameInput.HideSelection = true;
            this.fnameInput.IconLeft = null;
            this.fnameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.fnameInput.IconPadding = 10;
            this.fnameInput.IconRight = null;
            this.fnameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.fnameInput.Lines = new string[0];
            this.fnameInput.Location = new System.Drawing.Point(28, 166);
            this.fnameInput.MaxLength = 32767;
            this.fnameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.fnameInput.Modified = false;
            this.fnameInput.Multiline = false;
            this.fnameInput.Name = "fnameInput";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fnameInput.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.fnameInput.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fnameInput.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fnameInput.OnIdleState = stateProperties12;
            this.fnameInput.Padding = new System.Windows.Forms.Padding(3);
            this.fnameInput.PasswordChar = '\0';
            this.fnameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fnameInput.PlaceholderText = "First Name";
            this.fnameInput.ReadOnly = false;
            this.fnameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.fnameInput.SelectedText = "";
            this.fnameInput.SelectionLength = 0;
            this.fnameInput.SelectionStart = 0;
            this.fnameInput.ShortcutsEnabled = true;
            this.fnameInput.Size = new System.Drawing.Size(152, 39);
            this.fnameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.fnameInput.TabIndex = 12;
            this.fnameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.fnameInput.TextMarginBottom = 0;
            this.fnameInput.TextMarginLeft = 3;
            this.fnameInput.TextMarginTop = 1;
            this.fnameInput.TextPlaceholder = "First Name";
            this.fnameInput.UseSystemPasswordChar = false;
            this.fnameInput.WordWrap = true;
            // 
            // lnameInput
            // 
            this.lnameInput.AcceptsReturn = false;
            this.lnameInput.AcceptsTab = false;
            this.lnameInput.AnimationSpeed = 200;
            this.lnameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lnameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lnameInput.AutoSizeHeight = true;
            this.lnameInput.BackColor = System.Drawing.Color.Transparent;
            this.lnameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lnameInput.BackgroundImage")));
            this.lnameInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.lnameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.lnameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lnameInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.lnameInput.BorderRadius = 15;
            this.lnameInput.BorderThickness = 3;
            this.lnameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lnameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lnameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lnameInput.DefaultText = "";
            this.lnameInput.FillColor = System.Drawing.Color.White;
            this.lnameInput.HideSelection = true;
            this.lnameInput.IconLeft = null;
            this.lnameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lnameInput.IconPadding = 10;
            this.lnameInput.IconRight = null;
            this.lnameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lnameInput.Lines = new string[0];
            this.lnameInput.Location = new System.Drawing.Point(212, 166);
            this.lnameInput.MaxLength = 32767;
            this.lnameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.lnameInput.Modified = false;
            this.lnameInput.Multiline = false;
            this.lnameInput.Name = "lnameInput";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lnameInput.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lnameInput.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lnameInput.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lnameInput.OnIdleState = stateProperties16;
            this.lnameInput.Padding = new System.Windows.Forms.Padding(3);
            this.lnameInput.PasswordChar = '\0';
            this.lnameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lnameInput.PlaceholderText = "Last Name";
            this.lnameInput.ReadOnly = false;
            this.lnameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lnameInput.SelectedText = "";
            this.lnameInput.SelectionLength = 0;
            this.lnameInput.SelectionStart = 0;
            this.lnameInput.ShortcutsEnabled = true;
            this.lnameInput.Size = new System.Drawing.Size(152, 39);
            this.lnameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lnameInput.TabIndex = 11;
            this.lnameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.lnameInput.TextMarginBottom = 0;
            this.lnameInput.TextMarginLeft = 3;
            this.lnameInput.TextMarginTop = 1;
            this.lnameInput.TextPlaceholder = "Last Name";
            this.lnameInput.UseSystemPasswordChar = false;
            this.lnameInput.WordWrap = true;
            // 
            // titleInput
            // 
            this.titleInput.AcceptsReturn = false;
            this.titleInput.AcceptsTab = false;
            this.titleInput.AnimationSpeed = 200;
            this.titleInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.titleInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.titleInput.AutoSizeHeight = true;
            this.titleInput.BackColor = System.Drawing.Color.Transparent;
            this.titleInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("titleInput.BackgroundImage")));
            this.titleInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderRadius = 15;
            this.titleInput.BorderThickness = 3;
            this.titleInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.titleInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.titleInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.titleInput.DefaultText = "";
            this.titleInput.FillColor = System.Drawing.Color.White;
            this.titleInput.HideSelection = true;
            this.titleInput.IconLeft = null;
            this.titleInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.titleInput.IconPadding = 10;
            this.titleInput.IconRight = null;
            this.titleInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.titleInput.Lines = new string[0];
            this.titleInput.Location = new System.Drawing.Point(28, 360);
            this.titleInput.MaxLength = 32767;
            this.titleInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.titleInput.Modified = false;
            this.titleInput.Multiline = false;
            this.titleInput.Name = "titleInput";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.titleInput.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.titleInput.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.titleInput.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.titleInput.OnIdleState = stateProperties20;
            this.titleInput.Padding = new System.Windows.Forms.Padding(3);
            this.titleInput.PasswordChar = '\0';
            this.titleInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.titleInput.PlaceholderText = "Title";
            this.titleInput.ReadOnly = false;
            this.titleInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.titleInput.SelectedText = "";
            this.titleInput.SelectionLength = 0;
            this.titleInput.SelectionStart = 0;
            this.titleInput.ShortcutsEnabled = true;
            this.titleInput.Size = new System.Drawing.Size(336, 39);
            this.titleInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.titleInput.TabIndex = 19;
            this.titleInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.titleInput.TextMarginBottom = 0;
            this.titleInput.TextMarginLeft = 3;
            this.titleInput.TextMarginTop = 1;
            this.titleInput.TextPlaceholder = "Title";
            this.titleInput.UseSystemPasswordChar = false;
            this.titleInput.WordWrap = true;
            // 
            // designationInput
            // 
            this.designationInput.AcceptsReturn = false;
            this.designationInput.AcceptsTab = false;
            this.designationInput.AnimationSpeed = 200;
            this.designationInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.designationInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.designationInput.AutoSizeHeight = true;
            this.designationInput.BackColor = System.Drawing.Color.Transparent;
            this.designationInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("designationInput.BackgroundImage")));
            this.designationInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderRadius = 15;
            this.designationInput.BorderThickness = 3;
            this.designationInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.designationInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.designationInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.designationInput.DefaultText = "";
            this.designationInput.FillColor = System.Drawing.Color.White;
            this.designationInput.HideSelection = true;
            this.designationInput.IconLeft = null;
            this.designationInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.designationInput.IconPadding = 10;
            this.designationInput.IconRight = null;
            this.designationInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.designationInput.Lines = new string[0];
            this.designationInput.Location = new System.Drawing.Point(28, 415);
            this.designationInput.MaxLength = 32767;
            this.designationInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.designationInput.Modified = false;
            this.designationInput.Multiline = false;
            this.designationInput.Name = "designationInput";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.designationInput.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.designationInput.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.designationInput.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.designationInput.OnIdleState = stateProperties24;
            this.designationInput.Padding = new System.Windows.Forms.Padding(3);
            this.designationInput.PasswordChar = '\0';
            this.designationInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.designationInput.PlaceholderText = "Designation";
            this.designationInput.ReadOnly = false;
            this.designationInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.designationInput.SelectedText = "";
            this.designationInput.SelectionLength = 0;
            this.designationInput.SelectionStart = 0;
            this.designationInput.ShortcutsEnabled = true;
            this.designationInput.Size = new System.Drawing.Size(336, 39);
            this.designationInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.designationInput.TabIndex = 20;
            this.designationInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.designationInput.TextMarginBottom = 0;
            this.designationInput.TextMarginLeft = 3;
            this.designationInput.TextMarginTop = 1;
            this.designationInput.TextPlaceholder = "Designation";
            this.designationInput.UseSystemPasswordChar = false;
            this.designationInput.WordWrap = true;
            // 
            // statusInput
            // 
            this.statusInput.AcceptsReturn = false;
            this.statusInput.AcceptsTab = false;
            this.statusInput.AnimationSpeed = 200;
            this.statusInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.statusInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.statusInput.AutoSizeHeight = true;
            this.statusInput.BackColor = System.Drawing.Color.Transparent;
            this.statusInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statusInput.BackgroundImage")));
            this.statusInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderRadius = 15;
            this.statusInput.BorderThickness = 3;
            this.statusInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.statusInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.statusInput.DefaultText = "";
            this.statusInput.FillColor = System.Drawing.Color.White;
            this.statusInput.HideSelection = true;
            this.statusInput.IconLeft = null;
            this.statusInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.IconPadding = 10;
            this.statusInput.IconRight = null;
            this.statusInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.Lines = new string[0];
            this.statusInput.Location = new System.Drawing.Point(28, 471);
            this.statusInput.MaxLength = 32767;
            this.statusInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.statusInput.Modified = false;
            this.statusInput.Multiline = false;
            this.statusInput.Name = "statusInput";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.statusInput.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnIdleState = stateProperties28;
            this.statusInput.Padding = new System.Windows.Forms.Padding(3);
            this.statusInput.PasswordChar = '\0';
            this.statusInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.statusInput.PlaceholderText = "Status";
            this.statusInput.ReadOnly = false;
            this.statusInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.statusInput.SelectedText = "";
            this.statusInput.SelectionLength = 0;
            this.statusInput.SelectionStart = 0;
            this.statusInput.ShortcutsEnabled = true;
            this.statusInput.Size = new System.Drawing.Size(336, 39);
            this.statusInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.statusInput.TabIndex = 21;
            this.statusInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.statusInput.TextMarginBottom = 0;
            this.statusInput.TextMarginLeft = 3;
            this.statusInput.TextMarginTop = 1;
            this.statusInput.TextPlaceholder = "Status";
            this.statusInput.UseSystemPasswordChar = false;
            this.statusInput.WordWrap = true;
            // 
            // codeInput
            // 
            this.codeInput.AcceptsReturn = false;
            this.codeInput.AcceptsTab = false;
            this.codeInput.AnimationSpeed = 200;
            this.codeInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.codeInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.codeInput.AutoSizeHeight = true;
            this.codeInput.BackColor = System.Drawing.Color.Transparent;
            this.codeInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("codeInput.BackgroundImage")));
            this.codeInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderRadius = 15;
            this.codeInput.BorderThickness = 3;
            this.codeInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.codeInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.codeInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.codeInput.DefaultText = "";
            this.codeInput.FillColor = System.Drawing.Color.White;
            this.codeInput.HideSelection = true;
            this.codeInput.IconLeft = null;
            this.codeInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.codeInput.IconPadding = 10;
            this.codeInput.IconRight = null;
            this.codeInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.codeInput.Lines = new string[0];
            this.codeInput.Location = new System.Drawing.Point(113, 256);
            this.codeInput.MaxLength = 32767;
            this.codeInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.codeInput.Modified = false;
            this.codeInput.Multiline = false;
            this.codeInput.Name = "codeInput";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codeInput.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.codeInput.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codeInput.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codeInput.OnIdleState = stateProperties32;
            this.codeInput.Padding = new System.Windows.Forms.Padding(3);
            this.codeInput.PasswordChar = '\0';
            this.codeInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.codeInput.PlaceholderText = "Supervisor Code";
            this.codeInput.ReadOnly = false;
            this.codeInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.codeInput.SelectedText = "";
            this.codeInput.SelectionLength = 0;
            this.codeInput.SelectionStart = 0;
            this.codeInput.ShortcutsEnabled = true;
            this.codeInput.Size = new System.Drawing.Size(152, 39);
            this.codeInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.codeInput.TabIndex = 22;
            this.codeInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.codeInput.TextMarginBottom = 0;
            this.codeInput.TextMarginLeft = 3;
            this.codeInput.TextMarginTop = 1;
            this.codeInput.TextPlaceholder = "Supervisor Code";
            this.codeInput.UseSystemPasswordChar = false;
            this.codeInput.WordWrap = true;
            // 
            // FacultyAdd
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(388, 592);
            this.Controls.Add(this.codeInput);
            this.Controls.Add(this.statusInput);
            this.Controls.Add(this.designationInput);
            this.Controls.Add(this.titleInput);
            this.Controls.Add(this.guna2Button1);
            this.Controls.Add(this.bunifuImageButton2);
            this.Controls.Add(this.bunifuImageButton1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.eidInput);
            this.Controls.Add(this.emailInput);
            this.Controls.Add(this.fnameInput);
            this.Controls.Add(this.lnameInput);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FacultyAdd";
            this.Text = "FacultyAdd";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Guna.UI2.WinForms.Guna2Button guna2Button1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox eidInput;
        private Bunifu.UI.WinForms.BunifuTextBox emailInput;
        private Bunifu.UI.WinForms.BunifuTextBox fnameInput;
        private Bunifu.UI.WinForms.BunifuTextBox lnameInput;
        private Bunifu.UI.WinForms.BunifuTextBox titleInput;
        private Bunifu.UI.WinForms.BunifuTextBox designationInput;
        private Bunifu.UI.WinForms.BunifuTextBox statusInput;
        private Bunifu.UI.WinForms.BunifuTextBox codeInput;
    }
}