
namespace DbProjectFinal
{
    partial class FacultyEdit
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FacultyEdit));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.codeInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.statusInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.designationInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.titleInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2Button1 = new Guna.UI2.WinForms.Guna2Button();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.eidInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.emailInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.fnameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lnameInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // codeInput
            // 
            this.codeInput.AcceptsReturn = false;
            this.codeInput.AcceptsTab = false;
            this.codeInput.AnimationSpeed = 200;
            this.codeInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.codeInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.codeInput.AutoSizeHeight = true;
            this.codeInput.BackColor = System.Drawing.Color.Transparent;
            this.codeInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("codeInput.BackgroundImage")));
            this.codeInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.codeInput.BorderRadius = 15;
            this.codeInput.BorderThickness = 3;
            this.codeInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.codeInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.codeInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.codeInput.DefaultText = "";
            this.codeInput.FillColor = System.Drawing.Color.White;
            this.codeInput.HideSelection = true;
            this.codeInput.IconLeft = null;
            this.codeInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.codeInput.IconPadding = 10;
            this.codeInput.IconRight = null;
            this.codeInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.codeInput.Lines = new string[0];
            this.codeInput.Location = new System.Drawing.Point(97, 259);
            this.codeInput.MaxLength = 32767;
            this.codeInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.codeInput.Modified = false;
            this.codeInput.Multiline = false;
            this.codeInput.Name = "codeInput";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codeInput.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.codeInput.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codeInput.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codeInput.OnIdleState = stateProperties36;
            this.codeInput.Padding = new System.Windows.Forms.Padding(3);
            this.codeInput.PasswordChar = '\0';
            this.codeInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.codeInput.PlaceholderText = "Supervisor Code";
            this.codeInput.ReadOnly = false;
            this.codeInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.codeInput.SelectedText = "";
            this.codeInput.SelectionLength = 0;
            this.codeInput.SelectionStart = 0;
            this.codeInput.ShortcutsEnabled = true;
            this.codeInput.Size = new System.Drawing.Size(152, 39);
            this.codeInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.codeInput.TabIndex = 34;
            this.codeInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.codeInput.TextMarginBottom = 0;
            this.codeInput.TextMarginLeft = 3;
            this.codeInput.TextMarginTop = 1;
            this.codeInput.TextPlaceholder = "Supervisor Code";
            this.codeInput.UseSystemPasswordChar = false;
            this.codeInput.WordWrap = true;
            // 
            // statusInput
            // 
            this.statusInput.AcceptsReturn = false;
            this.statusInput.AcceptsTab = false;
            this.statusInput.AnimationSpeed = 200;
            this.statusInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.statusInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.statusInput.AutoSizeHeight = true;
            this.statusInput.BackColor = System.Drawing.Color.Transparent;
            this.statusInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statusInput.BackgroundImage")));
            this.statusInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderRadius = 15;
            this.statusInput.BorderThickness = 3;
            this.statusInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.statusInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.statusInput.DefaultText = "";
            this.statusInput.FillColor = System.Drawing.Color.White;
            this.statusInput.HideSelection = true;
            this.statusInput.IconLeft = null;
            this.statusInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.IconPadding = 10;
            this.statusInput.IconRight = null;
            this.statusInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.Lines = new string[0];
            this.statusInput.Location = new System.Drawing.Point(12, 474);
            this.statusInput.MaxLength = 32767;
            this.statusInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.statusInput.Modified = false;
            this.statusInput.Multiline = false;
            this.statusInput.Name = "statusInput";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.statusInput.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnIdleState = stateProperties40;
            this.statusInput.Padding = new System.Windows.Forms.Padding(3);
            this.statusInput.PasswordChar = '\0';
            this.statusInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.statusInput.PlaceholderText = "Status";
            this.statusInput.ReadOnly = false;
            this.statusInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.statusInput.SelectedText = "";
            this.statusInput.SelectionLength = 0;
            this.statusInput.SelectionStart = 0;
            this.statusInput.ShortcutsEnabled = true;
            this.statusInput.Size = new System.Drawing.Size(336, 39);
            this.statusInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.statusInput.TabIndex = 33;
            this.statusInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.statusInput.TextMarginBottom = 0;
            this.statusInput.TextMarginLeft = 3;
            this.statusInput.TextMarginTop = 1;
            this.statusInput.TextPlaceholder = "Status";
            this.statusInput.UseSystemPasswordChar = false;
            this.statusInput.WordWrap = true;
            // 
            // designationInput
            // 
            this.designationInput.AcceptsReturn = false;
            this.designationInput.AcceptsTab = false;
            this.designationInput.AnimationSpeed = 200;
            this.designationInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.designationInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.designationInput.AutoSizeHeight = true;
            this.designationInput.BackColor = System.Drawing.Color.Transparent;
            this.designationInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("designationInput.BackgroundImage")));
            this.designationInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.designationInput.BorderRadius = 15;
            this.designationInput.BorderThickness = 3;
            this.designationInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.designationInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.designationInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.designationInput.DefaultText = "";
            this.designationInput.FillColor = System.Drawing.Color.White;
            this.designationInput.HideSelection = true;
            this.designationInput.IconLeft = null;
            this.designationInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.designationInput.IconPadding = 10;
            this.designationInput.IconRight = null;
            this.designationInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.designationInput.Lines = new string[0];
            this.designationInput.Location = new System.Drawing.Point(12, 418);
            this.designationInput.MaxLength = 32767;
            this.designationInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.designationInput.Modified = false;
            this.designationInput.Multiline = false;
            this.designationInput.Name = "designationInput";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.designationInput.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.designationInput.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.designationInput.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.designationInput.OnIdleState = stateProperties44;
            this.designationInput.Padding = new System.Windows.Forms.Padding(3);
            this.designationInput.PasswordChar = '\0';
            this.designationInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.designationInput.PlaceholderText = "Designation";
            this.designationInput.ReadOnly = false;
            this.designationInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.designationInput.SelectedText = "";
            this.designationInput.SelectionLength = 0;
            this.designationInput.SelectionStart = 0;
            this.designationInput.ShortcutsEnabled = true;
            this.designationInput.Size = new System.Drawing.Size(336, 39);
            this.designationInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.designationInput.TabIndex = 32;
            this.designationInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.designationInput.TextMarginBottom = 0;
            this.designationInput.TextMarginLeft = 3;
            this.designationInput.TextMarginTop = 1;
            this.designationInput.TextPlaceholder = "Designation";
            this.designationInput.UseSystemPasswordChar = false;
            this.designationInput.WordWrap = true;
            // 
            // titleInput
            // 
            this.titleInput.AcceptsReturn = false;
            this.titleInput.AcceptsTab = false;
            this.titleInput.AnimationSpeed = 200;
            this.titleInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.titleInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.titleInput.AutoSizeHeight = true;
            this.titleInput.BackColor = System.Drawing.Color.Transparent;
            this.titleInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("titleInput.BackgroundImage")));
            this.titleInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.titleInput.BorderRadius = 15;
            this.titleInput.BorderThickness = 3;
            this.titleInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.titleInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.titleInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.titleInput.DefaultText = "";
            this.titleInput.FillColor = System.Drawing.Color.White;
            this.titleInput.HideSelection = true;
            this.titleInput.IconLeft = null;
            this.titleInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.titleInput.IconPadding = 10;
            this.titleInput.IconRight = null;
            this.titleInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.titleInput.Lines = new string[0];
            this.titleInput.Location = new System.Drawing.Point(12, 363);
            this.titleInput.MaxLength = 32767;
            this.titleInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.titleInput.Modified = false;
            this.titleInput.Multiline = false;
            this.titleInput.Name = "titleInput";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.titleInput.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.titleInput.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.titleInput.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.titleInput.OnIdleState = stateProperties48;
            this.titleInput.Padding = new System.Windows.Forms.Padding(3);
            this.titleInput.PasswordChar = '\0';
            this.titleInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.titleInput.PlaceholderText = "Title";
            this.titleInput.ReadOnly = false;
            this.titleInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.titleInput.SelectedText = "";
            this.titleInput.SelectionLength = 0;
            this.titleInput.SelectionStart = 0;
            this.titleInput.ShortcutsEnabled = true;
            this.titleInput.Size = new System.Drawing.Size(336, 39);
            this.titleInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.titleInput.TabIndex = 31;
            this.titleInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.titleInput.TextMarginBottom = 0;
            this.titleInput.TextMarginLeft = 3;
            this.titleInput.TextMarginTop = 1;
            this.titleInput.TextPlaceholder = "Title";
            this.titleInput.UseSystemPasswordChar = false;
            this.titleInput.WordWrap = true;
            // 
            // guna2Button1
            // 
            this.guna2Button1.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button1.BorderRadius = 22;
            this.guna2Button1.CheckedState.Parent = this.guna2Button1;
            this.guna2Button1.CustomImages.Parent = this.guna2Button1;
            this.guna2Button1.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button1.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button1.DisabledState.Parent = this.guna2Button1;
            this.guna2Button1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.guna2Button1.Font = new System.Drawing.Font("Palatino Linotype", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2Button1.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.guna2Button1.HoverState.Parent = this.guna2Button1;
            this.guna2Button1.Location = new System.Drawing.Point(69, 530);
            this.guna2Button1.Name = "guna2Button1";
            this.guna2Button1.ShadowDecoration.Parent = this.guna2Button1;
            this.guna2Button1.Size = new System.Drawing.Size(212, 37);
            this.guna2Button1.TabIndex = 30;
            this.guna2Button1.Text = "Update";
            this.guna2Button1.Click += new System.EventHandler(this.guna2Button1_Click);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 20;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(31, 29);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(297, 17);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.TabIndex = 29;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 20;
            this.bunifuImageButton2.ZoomSpeed = 10;
            this.bunifuImageButton2.Click += new System.EventHandler(this.bunifuImageButton2_Click);
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 20;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(95, 83);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(12, 60);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.TabIndex = 28;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 20;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Impact", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(133, 95);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(192, 36);
            this.label1.TabIndex = 27;
            this.label1.Text = "Faculty Details";
            // 
            // eidInput
            // 
            this.eidInput.AcceptsReturn = false;
            this.eidInput.AcceptsTab = false;
            this.eidInput.AnimationSpeed = 200;
            this.eidInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.eidInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.eidInput.AutoSizeHeight = true;
            this.eidInput.BackColor = System.Drawing.Color.Transparent;
            this.eidInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("eidInput.BackgroundImage")));
            this.eidInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.eidInput.BorderRadius = 15;
            this.eidInput.BorderThickness = 3;
            this.eidInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.eidInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.eidInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.eidInput.DefaultText = "";
            this.eidInput.FillColor = System.Drawing.Color.White;
            this.eidInput.HideSelection = true;
            this.eidInput.IconLeft = null;
            this.eidInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.eidInput.IconPadding = 10;
            this.eidInput.IconRight = null;
            this.eidInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.eidInput.Lines = new string[0];
            this.eidInput.Location = new System.Drawing.Point(97, 214);
            this.eidInput.MaxLength = 32767;
            this.eidInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.eidInput.Modified = false;
            this.eidInput.Multiline = false;
            this.eidInput.Name = "eidInput";
            stateProperties49.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.eidInput.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.eidInput.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.eidInput.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.eidInput.OnIdleState = stateProperties52;
            this.eidInput.Padding = new System.Windows.Forms.Padding(3);
            this.eidInput.PasswordChar = '\0';
            this.eidInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.eidInput.PlaceholderText = "Employee Id";
            this.eidInput.ReadOnly = false;
            this.eidInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.eidInput.SelectedText = "";
            this.eidInput.SelectionLength = 0;
            this.eidInput.SelectionStart = 0;
            this.eidInput.ShortcutsEnabled = true;
            this.eidInput.Size = new System.Drawing.Size(152, 39);
            this.eidInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.eidInput.TabIndex = 26;
            this.eidInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.eidInput.TextMarginBottom = 0;
            this.eidInput.TextMarginLeft = 3;
            this.eidInput.TextMarginTop = 1;
            this.eidInput.TextPlaceholder = "Employee Id";
            this.eidInput.UseSystemPasswordChar = false;
            this.eidInput.WordWrap = true;
            // 
            // emailInput
            // 
            this.emailInput.AcceptsReturn = false;
            this.emailInput.AcceptsTab = false;
            this.emailInput.AnimationSpeed = 200;
            this.emailInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailInput.AutoSizeHeight = true;
            this.emailInput.BackColor = System.Drawing.Color.Transparent;
            this.emailInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailInput.BackgroundImage")));
            this.emailInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.emailInput.BorderRadius = 15;
            this.emailInput.BorderThickness = 3;
            this.emailInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.emailInput.DefaultText = "";
            this.emailInput.FillColor = System.Drawing.Color.White;
            this.emailInput.HideSelection = true;
            this.emailInput.IconLeft = null;
            this.emailInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.IconPadding = 10;
            this.emailInput.IconRight = null;
            this.emailInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailInput.Lines = new string[0];
            this.emailInput.Location = new System.Drawing.Point(12, 307);
            this.emailInput.MaxLength = 32767;
            this.emailInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailInput.Modified = false;
            this.emailInput.Multiline = false;
            this.emailInput.Name = "emailInput";
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailInput.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailInput.OnIdleState = stateProperties56;
            this.emailInput.Padding = new System.Windows.Forms.Padding(3);
            this.emailInput.PasswordChar = '\0';
            this.emailInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailInput.PlaceholderText = "Email Address";
            this.emailInput.ReadOnly = false;
            this.emailInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailInput.SelectedText = "";
            this.emailInput.SelectionLength = 0;
            this.emailInput.SelectionStart = 0;
            this.emailInput.ShortcutsEnabled = true;
            this.emailInput.Size = new System.Drawing.Size(336, 39);
            this.emailInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailInput.TabIndex = 25;
            this.emailInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.emailInput.TextMarginBottom = 0;
            this.emailInput.TextMarginLeft = 3;
            this.emailInput.TextMarginTop = 1;
            this.emailInput.TextPlaceholder = "Email Address";
            this.emailInput.UseSystemPasswordChar = false;
            this.emailInput.WordWrap = true;
            // 
            // fnameInput
            // 
            this.fnameInput.AcceptsReturn = false;
            this.fnameInput.AcceptsTab = false;
            this.fnameInput.AnimationSpeed = 200;
            this.fnameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.fnameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.fnameInput.AutoSizeHeight = true;
            this.fnameInput.BackColor = System.Drawing.Color.Transparent;
            this.fnameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("fnameInput.BackgroundImage")));
            this.fnameInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.fnameInput.BorderRadius = 15;
            this.fnameInput.BorderThickness = 3;
            this.fnameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.fnameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.fnameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.fnameInput.DefaultText = "";
            this.fnameInput.FillColor = System.Drawing.Color.White;
            this.fnameInput.HideSelection = true;
            this.fnameInput.IconLeft = null;
            this.fnameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.fnameInput.IconPadding = 10;
            this.fnameInput.IconRight = null;
            this.fnameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.fnameInput.Lines = new string[0];
            this.fnameInput.Location = new System.Drawing.Point(12, 169);
            this.fnameInput.MaxLength = 32767;
            this.fnameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.fnameInput.Modified = false;
            this.fnameInput.Multiline = false;
            this.fnameInput.Name = "fnameInput";
            stateProperties57.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fnameInput.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.fnameInput.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fnameInput.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fnameInput.OnIdleState = stateProperties60;
            this.fnameInput.Padding = new System.Windows.Forms.Padding(3);
            this.fnameInput.PasswordChar = '\0';
            this.fnameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fnameInput.PlaceholderText = "First Name";
            this.fnameInput.ReadOnly = false;
            this.fnameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.fnameInput.SelectedText = "";
            this.fnameInput.SelectionLength = 0;
            this.fnameInput.SelectionStart = 0;
            this.fnameInput.ShortcutsEnabled = true;
            this.fnameInput.Size = new System.Drawing.Size(152, 39);
            this.fnameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.fnameInput.TabIndex = 24;
            this.fnameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.fnameInput.TextMarginBottom = 0;
            this.fnameInput.TextMarginLeft = 3;
            this.fnameInput.TextMarginTop = 1;
            this.fnameInput.TextPlaceholder = "First Name";
            this.fnameInput.UseSystemPasswordChar = false;
            this.fnameInput.WordWrap = true;
            // 
            // lnameInput
            // 
            this.lnameInput.AcceptsReturn = false;
            this.lnameInput.AcceptsTab = false;
            this.lnameInput.AnimationSpeed = 200;
            this.lnameInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lnameInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lnameInput.AutoSizeHeight = true;
            this.lnameInput.BackColor = System.Drawing.Color.Transparent;
            this.lnameInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lnameInput.BackgroundImage")));
            this.lnameInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.lnameInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.lnameInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lnameInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.lnameInput.BorderRadius = 15;
            this.lnameInput.BorderThickness = 3;
            this.lnameInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lnameInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lnameInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lnameInput.DefaultText = "";
            this.lnameInput.FillColor = System.Drawing.Color.White;
            this.lnameInput.HideSelection = true;
            this.lnameInput.IconLeft = null;
            this.lnameInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lnameInput.IconPadding = 10;
            this.lnameInput.IconRight = null;
            this.lnameInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lnameInput.Lines = new string[0];
            this.lnameInput.Location = new System.Drawing.Point(196, 169);
            this.lnameInput.MaxLength = 32767;
            this.lnameInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.lnameInput.Modified = false;
            this.lnameInput.Multiline = false;
            this.lnameInput.Name = "lnameInput";
            stateProperties61.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lnameInput.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lnameInput.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lnameInput.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lnameInput.OnIdleState = stateProperties64;
            this.lnameInput.Padding = new System.Windows.Forms.Padding(3);
            this.lnameInput.PasswordChar = '\0';
            this.lnameInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lnameInput.PlaceholderText = "Last Name";
            this.lnameInput.ReadOnly = false;
            this.lnameInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lnameInput.SelectedText = "";
            this.lnameInput.SelectionLength = 0;
            this.lnameInput.SelectionStart = 0;
            this.lnameInput.ShortcutsEnabled = true;
            this.lnameInput.Size = new System.Drawing.Size(152, 39);
            this.lnameInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lnameInput.TabIndex = 23;
            this.lnameInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.lnameInput.TextMarginBottom = 0;
            this.lnameInput.TextMarginLeft = 3;
            this.lnameInput.TextMarginTop = 1;
            this.lnameInput.TextPlaceholder = "Last Name";
            this.lnameInput.UseSystemPasswordChar = false;
            this.lnameInput.WordWrap = true;
            // 
            // FacultyEdit
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(385, 617);
            this.Controls.Add(this.codeInput);
            this.Controls.Add(this.statusInput);
            this.Controls.Add(this.designationInput);
            this.Controls.Add(this.titleInput);
            this.Controls.Add(this.guna2Button1);
            this.Controls.Add(this.bunifuImageButton2);
            this.Controls.Add(this.bunifuImageButton1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.eidInput);
            this.Controls.Add(this.emailInput);
            this.Controls.Add(this.fnameInput);
            this.Controls.Add(this.lnameInput);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FacultyEdit";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FacultyEdit";
            this.Load += new System.EventHandler(this.FacultyEdit_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox codeInput;
        private Bunifu.UI.WinForms.BunifuTextBox statusInput;
        private Bunifu.UI.WinForms.BunifuTextBox designationInput;
        private Bunifu.UI.WinForms.BunifuTextBox titleInput;
        private Guna.UI2.WinForms.Guna2Button guna2Button1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox eidInput;
        private Bunifu.UI.WinForms.BunifuTextBox emailInput;
        private Bunifu.UI.WinForms.BunifuTextBox fnameInput;
        private Bunifu.UI.WinForms.BunifuTextBox lnameInput;
    }
}