
namespace DbProjectFinal
{
    partial class FeedbackAdd
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FeedbackAdd));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.guna2Button1 = new Guna.UI2.WinForms.Guna2Button();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.featureInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.introInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.planningInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.methodologyInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.statusInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.commentInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.systemInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // guna2Button1
            // 
            this.guna2Button1.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button1.BorderRadius = 22;
            this.guna2Button1.CheckedState.Parent = this.guna2Button1;
            this.guna2Button1.CustomImages.Parent = this.guna2Button1;
            this.guna2Button1.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button1.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button1.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button1.DisabledState.Parent = this.guna2Button1;
            this.guna2Button1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.guna2Button1.Font = new System.Drawing.Font("Palatino Linotype", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2Button1.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.guna2Button1.HoverState.Parent = this.guna2Button1;
            this.guna2Button1.Location = new System.Drawing.Point(142, 507);
            this.guna2Button1.Name = "guna2Button1";
            this.guna2Button1.ShadowDecoration.Parent = this.guna2Button1;
            this.guna2Button1.Size = new System.Drawing.Size(199, 37);
            this.guna2Button1.TabIndex = 27;
            this.guna2Button1.Text = "Add Feedback";
            this.guna2Button1.Click += new System.EventHandler(this.guna2Button1_Click);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 20;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(31, 29);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(353, 8);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.TabIndex = 26;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 20;
            this.bunifuImageButton2.ZoomSpeed = 10;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 20;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(95, 83);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(68, 51);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.TabIndex = 25;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 20;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Impact", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(189, 86);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(130, 36);
            this.label1.TabIndex = 24;
            this.label1.Text = "Feedback";
            // 
            // featureInput
            // 
            this.featureInput.AcceptsReturn = false;
            this.featureInput.AcceptsTab = false;
            this.featureInput.AnimationSpeed = 200;
            this.featureInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.featureInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.featureInput.AutoSizeHeight = true;
            this.featureInput.BackColor = System.Drawing.Color.Transparent;
            this.featureInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("featureInput.BackgroundImage")));
            this.featureInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.featureInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.featureInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.featureInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.featureInput.BorderRadius = 15;
            this.featureInput.BorderThickness = 3;
            this.featureInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.featureInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.featureInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.featureInput.DefaultText = "";
            this.featureInput.FillColor = System.Drawing.Color.White;
            this.featureInput.HideSelection = true;
            this.featureInput.IconLeft = null;
            this.featureInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.featureInput.IconPadding = 10;
            this.featureInput.IconRight = null;
            this.featureInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.featureInput.Lines = new string[0];
            this.featureInput.Location = new System.Drawing.Point(262, 160);
            this.featureInput.MaxLength = 32767;
            this.featureInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.featureInput.Modified = false;
            this.featureInput.Multiline = true;
            this.featureInput.Name = "featureInput";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.featureInput.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.featureInput.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.featureInput.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.featureInput.OnIdleState = stateProperties4;
            this.featureInput.Padding = new System.Windows.Forms.Padding(3);
            this.featureInput.PasswordChar = '\0';
            this.featureInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.featureInput.PlaceholderText = "Features";
            this.featureInput.ReadOnly = false;
            this.featureInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.featureInput.SelectedText = "";
            this.featureInput.SelectionLength = 0;
            this.featureInput.SelectionStart = 0;
            this.featureInput.ShortcutsEnabled = true;
            this.featureInput.Size = new System.Drawing.Size(226, 82);
            this.featureInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.featureInput.TabIndex = 20;
            this.featureInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.featureInput.TextMarginBottom = 0;
            this.featureInput.TextMarginLeft = 3;
            this.featureInput.TextMarginTop = 1;
            this.featureInput.TextPlaceholder = "Features";
            this.featureInput.UseSystemPasswordChar = false;
            this.featureInput.WordWrap = true;
            // 
            // introInput
            // 
            this.introInput.AcceptsReturn = false;
            this.introInput.AcceptsTab = false;
            this.introInput.AnimationSpeed = 200;
            this.introInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.introInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.introInput.AutoSizeHeight = true;
            this.introInput.BackColor = System.Drawing.Color.Transparent;
            this.introInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("introInput.BackgroundImage")));
            this.introInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderRadius = 15;
            this.introInput.BorderThickness = 3;
            this.introInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.introInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.introInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.introInput.DefaultText = "";
            this.introInput.FillColor = System.Drawing.Color.White;
            this.introInput.HideSelection = true;
            this.introInput.IconLeft = null;
            this.introInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.introInput.IconPadding = 10;
            this.introInput.IconRight = null;
            this.introInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.introInput.Lines = new string[0];
            this.introInput.Location = new System.Drawing.Point(10, 160);
            this.introInput.MaxLength = 32767;
            this.introInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.introInput.Modified = false;
            this.introInput.Multiline = true;
            this.introInput.Name = "introInput";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.introInput.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.introInput.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.introInput.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.introInput.OnIdleState = stateProperties8;
            this.introInput.Padding = new System.Windows.Forms.Padding(3);
            this.introInput.PasswordChar = '\0';
            this.introInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.introInput.PlaceholderText = "Introduction";
            this.introInput.ReadOnly = false;
            this.introInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.introInput.SelectedText = "";
            this.introInput.SelectionLength = 0;
            this.introInput.SelectionStart = 0;
            this.introInput.ShortcutsEnabled = true;
            this.introInput.Size = new System.Drawing.Size(234, 82);
            this.introInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.introInput.TabIndex = 21;
            this.introInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.introInput.TextMarginBottom = 0;
            this.introInput.TextMarginLeft = 3;
            this.introInput.TextMarginTop = 1;
            this.introInput.TextPlaceholder = "Introduction";
            this.introInput.UseSystemPasswordChar = false;
            this.introInput.WordWrap = true;
            // 
            // planningInput
            // 
            this.planningInput.AcceptsReturn = false;
            this.planningInput.AcceptsTab = false;
            this.planningInput.AnimationSpeed = 200;
            this.planningInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.planningInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.planningInput.AutoSizeHeight = true;
            this.planningInput.BackColor = System.Drawing.Color.Transparent;
            this.planningInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("planningInput.BackgroundImage")));
            this.planningInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderRadius = 15;
            this.planningInput.BorderThickness = 3;
            this.planningInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.planningInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.planningInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.planningInput.DefaultText = "";
            this.planningInput.FillColor = System.Drawing.Color.White;
            this.planningInput.HideSelection = true;
            this.planningInput.IconLeft = null;
            this.planningInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.planningInput.IconPadding = 10;
            this.planningInput.IconRight = null;
            this.planningInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.planningInput.Lines = new string[0];
            this.planningInput.Location = new System.Drawing.Point(10, 354);
            this.planningInput.MaxLength = 32767;
            this.planningInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.planningInput.Modified = false;
            this.planningInput.Multiline = true;
            this.planningInput.Name = "planningInput";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.planningInput.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.planningInput.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.planningInput.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.planningInput.OnIdleState = stateProperties12;
            this.planningInput.Padding = new System.Windows.Forms.Padding(3);
            this.planningInput.PasswordChar = '\0';
            this.planningInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.planningInput.PlaceholderText = "Planning";
            this.planningInput.ReadOnly = false;
            this.planningInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.planningInput.SelectedText = "";
            this.planningInput.SelectionLength = 0;
            this.planningInput.SelectionStart = 0;
            this.planningInput.ShortcutsEnabled = true;
            this.planningInput.Size = new System.Drawing.Size(232, 75);
            this.planningInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.planningInput.TabIndex = 22;
            this.planningInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.planningInput.TextMarginBottom = 0;
            this.planningInput.TextMarginLeft = 3;
            this.planningInput.TextMarginTop = 1;
            this.planningInput.TextPlaceholder = "Planning";
            this.planningInput.UseSystemPasswordChar = false;
            this.planningInput.WordWrap = true;
            // 
            // methodologyInput
            // 
            this.methodologyInput.AcceptsReturn = false;
            this.methodologyInput.AcceptsTab = false;
            this.methodologyInput.AnimationSpeed = 200;
            this.methodologyInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.methodologyInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.methodologyInput.AutoSizeHeight = true;
            this.methodologyInput.BackColor = System.Drawing.Color.Transparent;
            this.methodologyInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("methodologyInput.BackgroundImage")));
            this.methodologyInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderRadius = 15;
            this.methodologyInput.BorderThickness = 3;
            this.methodologyInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.methodologyInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.methodologyInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.methodologyInput.DefaultText = "";
            this.methodologyInput.FillColor = System.Drawing.Color.White;
            this.methodologyInput.HideSelection = true;
            this.methodologyInput.IconLeft = null;
            this.methodologyInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.methodologyInput.IconPadding = 10;
            this.methodologyInput.IconRight = null;
            this.methodologyInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.methodologyInput.Lines = new string[0];
            this.methodologyInput.Location = new System.Drawing.Point(12, 255);
            this.methodologyInput.MaxLength = 32767;
            this.methodologyInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.methodologyInput.Modified = false;
            this.methodologyInput.Multiline = true;
            this.methodologyInput.Name = "methodologyInput";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.methodologyInput.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.methodologyInput.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.methodologyInput.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.methodologyInput.OnIdleState = stateProperties16;
            this.methodologyInput.Padding = new System.Windows.Forms.Padding(3);
            this.methodologyInput.PasswordChar = '\0';
            this.methodologyInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.methodologyInput.PlaceholderText = "Methodology";
            this.methodologyInput.ReadOnly = false;
            this.methodologyInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.methodologyInput.SelectedText = "";
            this.methodologyInput.SelectionLength = 0;
            this.methodologyInput.SelectionStart = 0;
            this.methodologyInput.ShortcutsEnabled = true;
            this.methodologyInput.Size = new System.Drawing.Size(232, 81);
            this.methodologyInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.methodologyInput.TabIndex = 23;
            this.methodologyInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.methodologyInput.TextMarginBottom = 0;
            this.methodologyInput.TextMarginLeft = 3;
            this.methodologyInput.TextMarginTop = 1;
            this.methodologyInput.TextPlaceholder = "Methodology";
            this.methodologyInput.UseSystemPasswordChar = false;
            this.methodologyInput.WordWrap = true;
            // 
            // statusInput
            // 
            this.statusInput.AcceptsReturn = false;
            this.statusInput.AcceptsTab = false;
            this.statusInput.AnimationSpeed = 200;
            this.statusInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.statusInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.statusInput.AutoSizeHeight = true;
            this.statusInput.BackColor = System.Drawing.Color.Transparent;
            this.statusInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statusInput.BackgroundImage")));
            this.statusInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderRadius = 15;
            this.statusInput.BorderThickness = 3;
            this.statusInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.statusInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.statusInput.DefaultText = "";
            this.statusInput.FillColor = System.Drawing.Color.White;
            this.statusInput.HideSelection = true;
            this.statusInput.IconLeft = null;
            this.statusInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.IconPadding = 10;
            this.statusInput.IconRight = null;
            this.statusInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.Lines = new string[0];
            this.statusInput.Location = new System.Drawing.Point(142, 452);
            this.statusInput.MaxLength = 32767;
            this.statusInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.statusInput.Modified = false;
            this.statusInput.Multiline = true;
            this.statusInput.Name = "statusInput";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.statusInput.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnIdleState = stateProperties20;
            this.statusInput.Padding = new System.Windows.Forms.Padding(3);
            this.statusInput.PasswordChar = '\0';
            this.statusInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.statusInput.PlaceholderText = "Status";
            this.statusInput.ReadOnly = false;
            this.statusInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.statusInput.SelectedText = "";
            this.statusInput.SelectionLength = 0;
            this.statusInput.SelectionStart = 0;
            this.statusInput.ShortcutsEnabled = true;
            this.statusInput.Size = new System.Drawing.Size(199, 39);
            this.statusInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.statusInput.TabIndex = 28;
            this.statusInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.statusInput.TextMarginBottom = 0;
            this.statusInput.TextMarginLeft = 3;
            this.statusInput.TextMarginTop = 1;
            this.statusInput.TextPlaceholder = "Status";
            this.statusInput.UseSystemPasswordChar = false;
            this.statusInput.WordWrap = true;
            // 
            // commentInput
            // 
            this.commentInput.AcceptsReturn = false;
            this.commentInput.AcceptsTab = false;
            this.commentInput.AnimationSpeed = 200;
            this.commentInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.commentInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.commentInput.AutoSizeHeight = true;
            this.commentInput.BackColor = System.Drawing.Color.Transparent;
            this.commentInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("commentInput.BackgroundImage")));
            this.commentInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderRadius = 15;
            this.commentInput.BorderThickness = 3;
            this.commentInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.commentInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.commentInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.commentInput.DefaultText = "";
            this.commentInput.FillColor = System.Drawing.Color.White;
            this.commentInput.HideSelection = true;
            this.commentInput.IconLeft = null;
            this.commentInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.commentInput.IconPadding = 10;
            this.commentInput.IconRight = null;
            this.commentInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.commentInput.Lines = new string[0];
            this.commentInput.Location = new System.Drawing.Point(262, 255);
            this.commentInput.MaxLength = 32767;
            this.commentInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.commentInput.Modified = false;
            this.commentInput.Multiline = true;
            this.commentInput.Name = "commentInput";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.commentInput.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.commentInput.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.commentInput.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.commentInput.OnIdleState = stateProperties24;
            this.commentInput.Padding = new System.Windows.Forms.Padding(3);
            this.commentInput.PasswordChar = '\0';
            this.commentInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.commentInput.PlaceholderText = "Comments";
            this.commentInput.ReadOnly = false;
            this.commentInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.commentInput.SelectedText = "";
            this.commentInput.SelectionLength = 0;
            this.commentInput.SelectionStart = 0;
            this.commentInput.ShortcutsEnabled = true;
            this.commentInput.Size = new System.Drawing.Size(226, 81);
            this.commentInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.commentInput.TabIndex = 29;
            this.commentInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.commentInput.TextMarginBottom = 0;
            this.commentInput.TextMarginLeft = 3;
            this.commentInput.TextMarginTop = 1;
            this.commentInput.TextPlaceholder = "Comments";
            this.commentInput.UseSystemPasswordChar = false;
            this.commentInput.WordWrap = true;
            // 
            // systemInput
            // 
            this.systemInput.AcceptsReturn = false;
            this.systemInput.AcceptsTab = false;
            this.systemInput.AnimationSpeed = 200;
            this.systemInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.systemInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.systemInput.AutoSizeHeight = true;
            this.systemInput.BackColor = System.Drawing.Color.Transparent;
            this.systemInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("systemInput.BackgroundImage")));
            this.systemInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderRadius = 15;
            this.systemInput.BorderThickness = 3;
            this.systemInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.systemInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.systemInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.systemInput.DefaultText = "";
            this.systemInput.FillColor = System.Drawing.Color.White;
            this.systemInput.HideSelection = true;
            this.systemInput.IconLeft = null;
            this.systemInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.systemInput.IconPadding = 10;
            this.systemInput.IconRight = null;
            this.systemInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.systemInput.Lines = new string[0];
            this.systemInput.Location = new System.Drawing.Point(262, 354);
            this.systemInput.MaxLength = 32767;
            this.systemInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.systemInput.Modified = false;
            this.systemInput.Multiline = true;
            this.systemInput.Name = "systemInput";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.systemInput.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.systemInput.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.systemInput.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.systemInput.OnIdleState = stateProperties28;
            this.systemInput.Padding = new System.Windows.Forms.Padding(3);
            this.systemInput.PasswordChar = '\0';
            this.systemInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.systemInput.PlaceholderText = "System Diagram";
            this.systemInput.ReadOnly = false;
            this.systemInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.systemInput.SelectedText = "";
            this.systemInput.SelectionLength = 0;
            this.systemInput.SelectionStart = 0;
            this.systemInput.ShortcutsEnabled = true;
            this.systemInput.Size = new System.Drawing.Size(226, 75);
            this.systemInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.systemInput.TabIndex = 30;
            this.systemInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.systemInput.TextMarginBottom = 0;
            this.systemInput.TextMarginLeft = 3;
            this.systemInput.TextMarginTop = 1;
            this.systemInput.TextPlaceholder = "System Diagram";
            this.systemInput.UseSystemPasswordChar = false;
            this.systemInput.WordWrap = true;
            // 
            // FeedbackAdd
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(498, 562);
            this.Controls.Add(this.systemInput);
            this.Controls.Add(this.commentInput);
            this.Controls.Add(this.statusInput);
            this.Controls.Add(this.guna2Button1);
            this.Controls.Add(this.bunifuImageButton2);
            this.Controls.Add(this.bunifuImageButton1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.methodologyInput);
            this.Controls.Add(this.planningInput);
            this.Controls.Add(this.introInput);
            this.Controls.Add(this.featureInput);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FeedbackAdd";
            this.Text = "FeedbackAdd";
            this.Load += new System.EventHandler(this.FeedbackAdd_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Guna.UI2.WinForms.Guna2Button guna2Button1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox featureInput;
        private Bunifu.UI.WinForms.BunifuTextBox introInput;
        private Bunifu.UI.WinForms.BunifuTextBox planningInput;
        private Bunifu.UI.WinForms.BunifuTextBox methodologyInput;
        private Bunifu.UI.WinForms.BunifuTextBox statusInput;
        private Bunifu.UI.WinForms.BunifuTextBox commentInput;
        private Bunifu.UI.WinForms.BunifuTextBox systemInput;
    }
}