
namespace DbProjectFinal
{
    partial class FeedbackEdit
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FeedbackEdit));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.systemInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.commentInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.statusInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.updateButton = new Guna.UI2.WinForms.Guna2Button();
            this.bunifuImageButton2 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.methodologyInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.planningInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.introInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.featureInput = new Bunifu.UI.WinForms.BunifuTextBox();
            this.guna2Button2 = new Guna.UI2.WinForms.Guna2Button();
            this.SuspendLayout();
            // 
            // systemInput
            // 
            this.systemInput.AcceptsReturn = false;
            this.systemInput.AcceptsTab = false;
            this.systemInput.AnimationSpeed = 200;
            this.systemInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.systemInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.systemInput.AutoSizeHeight = true;
            this.systemInput.BackColor = System.Drawing.Color.Transparent;
            this.systemInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("systemInput.BackgroundImage")));
            this.systemInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.systemInput.BorderRadius = 15;
            this.systemInput.BorderThickness = 3;
            this.systemInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.systemInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.systemInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.systemInput.DefaultText = "";
            this.systemInput.Enabled = false;
            this.systemInput.FillColor = System.Drawing.Color.White;
            this.systemInput.HideSelection = true;
            this.systemInput.IconLeft = null;
            this.systemInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.systemInput.IconPadding = 10;
            this.systemInput.IconRight = null;
            this.systemInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.systemInput.Lines = new string[0];
            this.systemInput.Location = new System.Drawing.Point(264, 370);
            this.systemInput.MaxLength = 32767;
            this.systemInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.systemInput.Modified = false;
            this.systemInput.Multiline = true;
            this.systemInput.Name = "systemInput";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.systemInput.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.systemInput.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.systemInput.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.systemInput.OnIdleState = stateProperties32;
            this.systemInput.Padding = new System.Windows.Forms.Padding(3);
            this.systemInput.PasswordChar = '\0';
            this.systemInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.systemInput.PlaceholderText = "System Diagram";
            this.systemInput.ReadOnly = false;
            this.systemInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.systemInput.SelectedText = "";
            this.systemInput.SelectionLength = 0;
            this.systemInput.SelectionStart = 0;
            this.systemInput.ShortcutsEnabled = true;
            this.systemInput.Size = new System.Drawing.Size(226, 75);
            this.systemInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.systemInput.TabIndex = 41;
            this.systemInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.systemInput.TextMarginBottom = 0;
            this.systemInput.TextMarginLeft = 3;
            this.systemInput.TextMarginTop = 1;
            this.systemInput.TextPlaceholder = "System Diagram";
            this.systemInput.UseSystemPasswordChar = false;
            this.systemInput.WordWrap = true;
            // 
            // commentInput
            // 
            this.commentInput.AcceptsReturn = false;
            this.commentInput.AcceptsTab = false;
            this.commentInput.AnimationSpeed = 200;
            this.commentInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.commentInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.commentInput.AutoSizeHeight = true;
            this.commentInput.BackColor = System.Drawing.Color.Transparent;
            this.commentInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("commentInput.BackgroundImage")));
            this.commentInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.commentInput.BorderRadius = 15;
            this.commentInput.BorderThickness = 3;
            this.commentInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.commentInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.commentInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.commentInput.DefaultText = "";
            this.commentInput.Enabled = false;
            this.commentInput.FillColor = System.Drawing.Color.White;
            this.commentInput.HideSelection = true;
            this.commentInput.IconLeft = null;
            this.commentInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.commentInput.IconPadding = 10;
            this.commentInput.IconRight = null;
            this.commentInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.commentInput.Lines = new string[0];
            this.commentInput.Location = new System.Drawing.Point(264, 271);
            this.commentInput.MaxLength = 32767;
            this.commentInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.commentInput.Modified = false;
            this.commentInput.Multiline = true;
            this.commentInput.Name = "commentInput";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.commentInput.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.commentInput.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.commentInput.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.commentInput.OnIdleState = stateProperties36;
            this.commentInput.Padding = new System.Windows.Forms.Padding(3);
            this.commentInput.PasswordChar = '\0';
            this.commentInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.commentInput.PlaceholderText = "Comments";
            this.commentInput.ReadOnly = false;
            this.commentInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.commentInput.SelectedText = "";
            this.commentInput.SelectionLength = 0;
            this.commentInput.SelectionStart = 0;
            this.commentInput.ShortcutsEnabled = true;
            this.commentInput.Size = new System.Drawing.Size(226, 81);
            this.commentInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.commentInput.TabIndex = 40;
            this.commentInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.commentInput.TextMarginBottom = 0;
            this.commentInput.TextMarginLeft = 3;
            this.commentInput.TextMarginTop = 1;
            this.commentInput.TextPlaceholder = "Comments";
            this.commentInput.UseSystemPasswordChar = false;
            this.commentInput.WordWrap = true;
            // 
            // statusInput
            // 
            this.statusInput.AcceptsReturn = false;
            this.statusInput.AcceptsTab = false;
            this.statusInput.AnimationSpeed = 200;
            this.statusInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.statusInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.statusInput.AutoSizeHeight = true;
            this.statusInput.BackColor = System.Drawing.Color.Transparent;
            this.statusInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statusInput.BackgroundImage")));
            this.statusInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.statusInput.BorderRadius = 15;
            this.statusInput.BorderThickness = 3;
            this.statusInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.statusInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.statusInput.DefaultText = "";
            this.statusInput.Enabled = false;
            this.statusInput.FillColor = System.Drawing.Color.White;
            this.statusInput.HideSelection = true;
            this.statusInput.IconLeft = null;
            this.statusInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.IconPadding = 10;
            this.statusInput.IconRight = null;
            this.statusInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusInput.Lines = new string[0];
            this.statusInput.Location = new System.Drawing.Point(144, 468);
            this.statusInput.MaxLength = 32767;
            this.statusInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.statusInput.Modified = false;
            this.statusInput.Multiline = true;
            this.statusInput.Name = "statusInput";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.statusInput.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusInput.OnIdleState = stateProperties40;
            this.statusInput.Padding = new System.Windows.Forms.Padding(3);
            this.statusInput.PasswordChar = '\0';
            this.statusInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.statusInput.PlaceholderText = "Status";
            this.statusInput.ReadOnly = false;
            this.statusInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.statusInput.SelectedText = "";
            this.statusInput.SelectionLength = 0;
            this.statusInput.SelectionStart = 0;
            this.statusInput.ShortcutsEnabled = true;
            this.statusInput.Size = new System.Drawing.Size(199, 39);
            this.statusInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.statusInput.TabIndex = 39;
            this.statusInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.statusInput.TextMarginBottom = 0;
            this.statusInput.TextMarginLeft = 3;
            this.statusInput.TextMarginTop = 1;
            this.statusInput.TextPlaceholder = "Status";
            this.statusInput.UseSystemPasswordChar = false;
            this.statusInput.WordWrap = true;
            // 
            // updateButton
            // 
            this.updateButton.BackColor = System.Drawing.Color.Transparent;
            this.updateButton.BorderRadius = 22;
            this.updateButton.CheckedState.Parent = this.updateButton;
            this.updateButton.CustomImages.Parent = this.updateButton;
            this.updateButton.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.updateButton.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.updateButton.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.updateButton.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.updateButton.DisabledState.Parent = this.updateButton;
            this.updateButton.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.updateButton.Font = new System.Drawing.Font("Palatino Linotype", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.updateButton.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.updateButton.HoverState.Parent = this.updateButton;
            this.updateButton.Location = new System.Drawing.Point(14, 523);
            this.updateButton.Name = "updateButton";
            this.updateButton.ShadowDecoration.Parent = this.updateButton;
            this.updateButton.Size = new System.Drawing.Size(199, 37);
            this.updateButton.TabIndex = 38;
            this.updateButton.Text = "Update Feedback";
            this.updateButton.Visible = false;
            this.updateButton.Click += new System.EventHandler(this.updateButton_Click);
            // 
            // bunifuImageButton2
            // 
            this.bunifuImageButton2.ActiveImage = null;
            this.bunifuImageButton2.AllowAnimations = true;
            this.bunifuImageButton2.AllowBuffering = false;
            this.bunifuImageButton2.AllowToggling = false;
            this.bunifuImageButton2.AllowZooming = true;
            this.bunifuImageButton2.AllowZoomingOnFocus = false;
            this.bunifuImageButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton2.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.ErrorImage")));
            this.bunifuImageButton2.FadeWhenInactive = false;
            this.bunifuImageButton2.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.Image")));
            this.bunifuImageButton2.ImageActive = null;
            this.bunifuImageButton2.ImageLocation = null;
            this.bunifuImageButton2.ImageMargin = 20;
            this.bunifuImageButton2.ImageSize = new System.Drawing.Size(31, 29);
            this.bunifuImageButton2.ImageZoomSize = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton2.InitialImage")));
            this.bunifuImageButton2.Location = new System.Drawing.Point(428, 24);
            this.bunifuImageButton2.Name = "bunifuImageButton2";
            this.bunifuImageButton2.Rotation = 0;
            this.bunifuImageButton2.ShowActiveImage = true;
            this.bunifuImageButton2.ShowCursorChanges = true;
            this.bunifuImageButton2.ShowImageBorders = true;
            this.bunifuImageButton2.ShowSizeMarkers = false;
            this.bunifuImageButton2.Size = new System.Drawing.Size(51, 49);
            this.bunifuImageButton2.TabIndex = 37;
            this.bunifuImageButton2.ToolTipText = "";
            this.bunifuImageButton2.WaitOnLoad = false;
            this.bunifuImageButton2.Zoom = 20;
            this.bunifuImageButton2.ZoomSpeed = 10;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 20;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(95, 83);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(70, 67);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(115, 103);
            this.bunifuImageButton1.TabIndex = 36;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 20;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Impact", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(191, 102);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(130, 36);
            this.label1.TabIndex = 35;
            this.label1.Text = "Feedback";
            // 
            // methodologyInput
            // 
            this.methodologyInput.AcceptsReturn = false;
            this.methodologyInput.AcceptsTab = false;
            this.methodologyInput.AnimationSpeed = 200;
            this.methodologyInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.methodologyInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.methodologyInput.AutoSizeHeight = true;
            this.methodologyInput.BackColor = System.Drawing.Color.Transparent;
            this.methodologyInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("methodologyInput.BackgroundImage")));
            this.methodologyInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.methodologyInput.BorderRadius = 15;
            this.methodologyInput.BorderThickness = 3;
            this.methodologyInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.methodologyInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.methodologyInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.methodologyInput.DefaultText = "";
            this.methodologyInput.Enabled = false;
            this.methodologyInput.FillColor = System.Drawing.Color.White;
            this.methodologyInput.HideSelection = true;
            this.methodologyInput.IconLeft = null;
            this.methodologyInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.methodologyInput.IconPadding = 10;
            this.methodologyInput.IconRight = null;
            this.methodologyInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.methodologyInput.Lines = new string[0];
            this.methodologyInput.Location = new System.Drawing.Point(14, 271);
            this.methodologyInput.MaxLength = 32767;
            this.methodologyInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.methodologyInput.Modified = false;
            this.methodologyInput.Multiline = true;
            this.methodologyInput.Name = "methodologyInput";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.methodologyInput.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.methodologyInput.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.methodologyInput.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.methodologyInput.OnIdleState = stateProperties44;
            this.methodologyInput.Padding = new System.Windows.Forms.Padding(3);
            this.methodologyInput.PasswordChar = '\0';
            this.methodologyInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.methodologyInput.PlaceholderText = "Methodology";
            this.methodologyInput.ReadOnly = false;
            this.methodologyInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.methodologyInput.SelectedText = "";
            this.methodologyInput.SelectionLength = 0;
            this.methodologyInput.SelectionStart = 0;
            this.methodologyInput.ShortcutsEnabled = true;
            this.methodologyInput.Size = new System.Drawing.Size(232, 81);
            this.methodologyInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.methodologyInput.TabIndex = 34;
            this.methodologyInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.methodologyInput.TextMarginBottom = 0;
            this.methodologyInput.TextMarginLeft = 3;
            this.methodologyInput.TextMarginTop = 1;
            this.methodologyInput.TextPlaceholder = "Methodology";
            this.methodologyInput.UseSystemPasswordChar = false;
            this.methodologyInput.WordWrap = true;
            // 
            // planningInput
            // 
            this.planningInput.AcceptsReturn = false;
            this.planningInput.AcceptsTab = false;
            this.planningInput.AnimationSpeed = 200;
            this.planningInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.planningInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.planningInput.AutoSizeHeight = true;
            this.planningInput.BackColor = System.Drawing.Color.Transparent;
            this.planningInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("planningInput.BackgroundImage")));
            this.planningInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.planningInput.BorderRadius = 15;
            this.planningInput.BorderThickness = 3;
            this.planningInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.planningInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.planningInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.planningInput.DefaultText = "";
            this.planningInput.Enabled = false;
            this.planningInput.FillColor = System.Drawing.Color.White;
            this.planningInput.HideSelection = true;
            this.planningInput.IconLeft = null;
            this.planningInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.planningInput.IconPadding = 10;
            this.planningInput.IconRight = null;
            this.planningInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.planningInput.Lines = new string[0];
            this.planningInput.Location = new System.Drawing.Point(12, 370);
            this.planningInput.MaxLength = 32767;
            this.planningInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.planningInput.Modified = false;
            this.planningInput.Multiline = true;
            this.planningInput.Name = "planningInput";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.planningInput.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.planningInput.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.planningInput.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.planningInput.OnIdleState = stateProperties48;
            this.planningInput.Padding = new System.Windows.Forms.Padding(3);
            this.planningInput.PasswordChar = '\0';
            this.planningInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.planningInput.PlaceholderText = "Planning";
            this.planningInput.ReadOnly = false;
            this.planningInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.planningInput.SelectedText = "";
            this.planningInput.SelectionLength = 0;
            this.planningInput.SelectionStart = 0;
            this.planningInput.ShortcutsEnabled = true;
            this.planningInput.Size = new System.Drawing.Size(232, 75);
            this.planningInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.planningInput.TabIndex = 33;
            this.planningInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.planningInput.TextMarginBottom = 0;
            this.planningInput.TextMarginLeft = 3;
            this.planningInput.TextMarginTop = 1;
            this.planningInput.TextPlaceholder = "Planning";
            this.planningInput.UseSystemPasswordChar = false;
            this.planningInput.WordWrap = true;
            // 
            // introInput
            // 
            this.introInput.AcceptsReturn = false;
            this.introInput.AcceptsTab = false;
            this.introInput.AnimationSpeed = 200;
            this.introInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.introInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.introInput.AutoSizeHeight = true;
            this.introInput.BackColor = System.Drawing.Color.Transparent;
            this.introInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("introInput.BackgroundImage")));
            this.introInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.introInput.BorderRadius = 15;
            this.introInput.BorderThickness = 3;
            this.introInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.introInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.introInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.introInput.DefaultText = "";
            this.introInput.Enabled = false;
            this.introInput.FillColor = System.Drawing.Color.White;
            this.introInput.HideSelection = true;
            this.introInput.IconLeft = null;
            this.introInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.introInput.IconPadding = 10;
            this.introInput.IconRight = null;
            this.introInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.introInput.Lines = new string[0];
            this.introInput.Location = new System.Drawing.Point(12, 176);
            this.introInput.MaxLength = 32767;
            this.introInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.introInput.Modified = false;
            this.introInput.Multiline = true;
            this.introInput.Name = "introInput";
            stateProperties49.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.introInput.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.introInput.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.introInput.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.introInput.OnIdleState = stateProperties52;
            this.introInput.Padding = new System.Windows.Forms.Padding(3);
            this.introInput.PasswordChar = '\0';
            this.introInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.introInput.PlaceholderText = "Introduction";
            this.introInput.ReadOnly = false;
            this.introInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.introInput.SelectedText = "";
            this.introInput.SelectionLength = 0;
            this.introInput.SelectionStart = 0;
            this.introInput.ShortcutsEnabled = true;
            this.introInput.Size = new System.Drawing.Size(234, 82);
            this.introInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.introInput.TabIndex = 32;
            this.introInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.introInput.TextMarginBottom = 0;
            this.introInput.TextMarginLeft = 3;
            this.introInput.TextMarginTop = 1;
            this.introInput.TextPlaceholder = "Introduction";
            this.introInput.UseSystemPasswordChar = false;
            this.introInput.WordWrap = true;
            // 
            // featureInput
            // 
            this.featureInput.AcceptsReturn = false;
            this.featureInput.AcceptsTab = false;
            this.featureInput.AnimationSpeed = 200;
            this.featureInput.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.featureInput.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.featureInput.AutoSizeHeight = true;
            this.featureInput.BackColor = System.Drawing.Color.Transparent;
            this.featureInput.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("featureInput.BackgroundImage")));
            this.featureInput.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.featureInput.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.featureInput.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.featureInput.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.featureInput.BorderRadius = 15;
            this.featureInput.BorderThickness = 3;
            this.featureInput.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.featureInput.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.featureInput.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.featureInput.DefaultText = "";
            this.featureInput.Enabled = false;
            this.featureInput.FillColor = System.Drawing.Color.White;
            this.featureInput.HideSelection = true;
            this.featureInput.IconLeft = null;
            this.featureInput.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.featureInput.IconPadding = 10;
            this.featureInput.IconRight = null;
            this.featureInput.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.featureInput.Lines = new string[0];
            this.featureInput.Location = new System.Drawing.Point(264, 176);
            this.featureInput.MaxLength = 32767;
            this.featureInput.MinimumSize = new System.Drawing.Size(1, 1);
            this.featureInput.Modified = false;
            this.featureInput.Multiline = true;
            this.featureInput.Name = "featureInput";
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.featureInput.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.featureInput.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.featureInput.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.featureInput.OnIdleState = stateProperties56;
            this.featureInput.Padding = new System.Windows.Forms.Padding(3);
            this.featureInput.PasswordChar = '\0';
            this.featureInput.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.featureInput.PlaceholderText = "Features";
            this.featureInput.ReadOnly = false;
            this.featureInput.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.featureInput.SelectedText = "";
            this.featureInput.SelectionLength = 0;
            this.featureInput.SelectionStart = 0;
            this.featureInput.ShortcutsEnabled = true;
            this.featureInput.Size = new System.Drawing.Size(226, 82);
            this.featureInput.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.featureInput.TabIndex = 31;
            this.featureInput.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.featureInput.TextMarginBottom = 0;
            this.featureInput.TextMarginLeft = 3;
            this.featureInput.TextMarginTop = 1;
            this.featureInput.TextPlaceholder = "Features";
            this.featureInput.UseSystemPasswordChar = false;
            this.featureInput.WordWrap = true;
            // 
            // guna2Button2
            // 
            this.guna2Button2.BackColor = System.Drawing.Color.Transparent;
            this.guna2Button2.BorderRadius = 22;
            this.guna2Button2.CheckedState.Parent = this.guna2Button2;
            this.guna2Button2.CustomImages.Parent = this.guna2Button2;
            this.guna2Button2.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button2.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            this.guna2Button2.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(169)))), ((int)(((byte)(169)))), ((int)(((byte)(169)))));
            this.guna2Button2.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.guna2Button2.DisabledState.Parent = this.guna2Button2;
            this.guna2Button2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(124)))), ((int)(((byte)(188)))));
            this.guna2Button2.Font = new System.Drawing.Font("Palatino Linotype", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.guna2Button2.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.guna2Button2.HoverState.Parent = this.guna2Button2;
            this.guna2Button2.Location = new System.Drawing.Point(252, 523);
            this.guna2Button2.Name = "guna2Button2";
            this.guna2Button2.ShadowDecoration.Parent = this.guna2Button2;
            this.guna2Button2.Size = new System.Drawing.Size(199, 37);
            this.guna2Button2.TabIndex = 42;
            this.guna2Button2.Text = "Edit Feedback";
            this.guna2Button2.Click += new System.EventHandler(this.guna2Button2_Click);
            // 
            // FeedbackEdit
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(509, 597);
            this.Controls.Add(this.guna2Button2);
            this.Controls.Add(this.systemInput);
            this.Controls.Add(this.commentInput);
            this.Controls.Add(this.statusInput);
            this.Controls.Add(this.updateButton);
            this.Controls.Add(this.bunifuImageButton2);
            this.Controls.Add(this.bunifuImageButton1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.methodologyInput);
            this.Controls.Add(this.planningInput);
            this.Controls.Add(this.introInput);
            this.Controls.Add(this.featureInput);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FeedbackEdit";
            this.Text = "FeedbackEdit";
            this.Load += new System.EventHandler(this.FeedbackEdit_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox systemInput;
        private Bunifu.UI.WinForms.BunifuTextBox commentInput;
        private Bunifu.UI.WinForms.BunifuTextBox statusInput;
        private Guna.UI2.WinForms.Guna2Button updateButton;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton2;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox methodologyInput;
        private Bunifu.UI.WinForms.BunifuTextBox planningInput;
        private Bunifu.UI.WinForms.BunifuTextBox introInput;
        private Bunifu.UI.WinForms.BunifuTextBox featureInput;
        private Guna.UI2.WinForms.Guna2Button guna2Button2;
    }
}